name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint || true   # won’t fail build until we add eslint config

      - name: Typecheck
        run: pnpm -r exec tsc -p tsconfig.json --noEmit

      - name: Build all packages
        run: pnpm -r build

      - name: Run tests
        run: pnpm -r test --if-present
